name: CI & CD

on:
  push:
    branches:
      - main
      - staging
      - develop
  pull_request:
    branches:
      - main
      - staging
      - develop

jobs:
  osv-scanner:
    name: OSV Scan Vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
          cache-dependency-path: go.sum

      - name: Check out code
        uses: actions/checkout@v3

      - name: Lint Go Code
        run: |
          go version
          go install github.com/google/osv-scanner/cmd/osv-scanner@v1
          make osv

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
          cache-dependency-path: go.sum

      - name: Check out code
        uses: actions/checkout@v3

      - name: Lint Go Code
        run: |
          go version
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.53.3
          make lint
          
      
